// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv

import dotenv from "dotenv";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    seed: "tsx ./prisma/seed.ts",
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env["DATABASE_URL"]!,
  },
});
